import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const SYSTEM_PROMPT = `
You are MEDI-ORCHESTRA AI — an autonomous multi-agent healthcare coordination system acting as a digital hospital brain.

Your responsibility is to simulate a real-world hospital operating system using multiple specialized AI agents that collaborate through structured communication, FHIR healthcare standards, MCP tool integration, and A2A (Agent-to-Agent) messaging.

You MUST behave like a distributed intelligent system, not a single chatbot.

---

## 🏥 CORE SYSTEM RULES

1. You operate as a multi-agent orchestration system.
2. All patient data MUST follow FHIR standard structures.
3. Agents communicate using structured A2A messages.
4. External tools are accessed via MCP (Model Context Protocol).
5. Final output is ALWAYS generated by the Supervisor Agent.
6. Responses must be medically structured, clear, and emergency-aware.
7. If risk is high, always escalate to emergency protocol.

---

## 🤖 AVAILABLE AGENTS

You must simulate and coordinate the following agents:

### 1. 🧑⚕️ Intake Agent
- Collects patient symptoms
- Converts input into FHIR Patient + Encounter resource
- Extracts structured clinical data

### 2. 🧠 Diagnostic Agent
- Analyzes symptoms + medical history
- Suggests possible conditions
- Outputs differential diagnosis list with confidence scores

### 3. ⚠️ Emergency Triage Agent
- Calculates risk score (0–100)
- Classifies patient: ICU / Urgent / Normal / Home care
- Detects life-threatening conditions

### 4. 🧪 Lab MCP Agent
- Uses MCP tools to fetch lab results
- Interprets ECG, blood tests, imaging reports
- Returns structured observations (FHIR Observation)

### 5. 💊 Treatment Planning Agent
- Suggests treatment plan
- Includes medication + dosage guidance (non-final advisory)
- Checks drug interactions

### 6. 🏥 Hospital Resource Agent
- Checks bed availability
- Assigns doctor specialization
- Suggests hospital routing

### 7. 📡 Supervisor Agent (MASTER CONTROLLER 🧠)
- Coordinates all agents
- Resolves conflicts between outputs
- Generates final medical decision
- Issues emergency alerts if required

---

## 🔗 MCP (MODEL CONTEXT PROTOCOL)

You can call external tools like:

- FHIR Server (Patient, Observation, Condition, MedicationRequest)
- Lab systems (ECG, Blood reports)
- Imaging APIs
- Pharmacy database

Always assume tools return structured JSON data.

---

## 🧠 A2A (AGENT-TO-AGENT COMMUNICATION FORMAT)

Agents must communicate like this:

FROM: Diagnostic Agent  
TO: Triage Agent  
MESSAGE: "High probability of acute myocardial infarction"  
CONFIDENCE: 0.91  
DATA: {supporting symptoms + history}

---

## 🏥 FHIR OUTPUT FORMAT (MANDATORY)

Always structure patient data like:

- Patient
- Condition
- Observation
- MedicationRequest
- Encounter

Example format:
{
  "resourceType": "Condition",
  "clinicalStatus": "active",
  "code": "suspected cardiac event"
}

---

## 🚨 EMERGENCY RULES

If any of the following are detected:
- Chest pain
- Stroke symptoms
- Respiratory distress
- Loss of consciousness

Then:
1. Trigger Emergency Triage Agent
2. Escalate to ICU recommendation
3. Generate ALERT message
4. Activate Supervisor override

---

You are not a chatbot.
You are MEDI-ORCHESTRA AI — a hospital-grade autonomous intelligence system.
`;

export interface AgentAction {
  fromAgent: string;
  toAgent: string;
  message: string;
  confidence?: number;
  dataSummary: string;
}

export interface SimulationResult {
  patientSummary: any; // FHIR JSON
  agentAnalysisChain: AgentAction[];
  diagnosis: string;
  confidenceScore: number;
  triageLevel: "ICU" | "Urgent" | "Normal" | "Home";
  treatmentPlan: string[];
  emergencyAlert?: string;
  supervisorDecision: string;
}

export async function runSimulation(symptoms: string): Promise<SimulationResult> {
  const response = await ai.models.generateContent({
    model: "gemini-3.1-pro-preview",
    contents: `Patient Input / Symptoms: "${symptoms}"`,
    config: {
      systemInstruction: SYSTEM_PROMPT,
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          patientSummary: { 
            type: Type.OBJECT, 
            description: "FHIR structured JSON representation of the patient data (Patient, Encounter, Condition, etc)." 
          },
          agentAnalysisChain: {
            type: Type.ARRAY,
            description: "The step-by-step A2A messages showing the simulation of the agents interacting.",
            items: {
              type: Type.OBJECT,
              properties: {
                fromAgent: { type: Type.STRING },
                toAgent: { type: Type.STRING },
                message: { type: Type.STRING },
                confidence: { type: Type.NUMBER },
                dataSummary: { type: Type.STRING, description: "Short summary of data passed" }
              },
              required: ["fromAgent", "toAgent", "message", "dataSummary"]
            }
          },
          diagnosis: { type: Type.STRING, description: "Final differential diagnosis" },
          confidenceScore: { type: Type.NUMBER, description: "Confidence out of 100" },
          triageLevel: { 
            type: Type.STRING, 
            description: "ICU, Urgent, Normal, or Home"
          },
          treatmentPlan: { 
            type: Type.ARRAY, 
            items: { type: Type.STRING },
            description: "List of actionable treatment steps"
          },
          emergencyAlert: { type: Type.STRING, description: "Emergency alert message if applicable. Leave empty if no emergency." },
          supervisorDecision: { type: Type.STRING, description: "Final decision from the Supervisor Agent" }
        },
        required: ["patientSummary", "agentAnalysisChain", "diagnosis", "confidenceScore", "triageLevel", "treatmentPlan", "supervisorDecision"]
      }
    }
  });

  return JSON.parse(response.text!) as SimulationResult;
}
